---
  project_name: 'Plecoptera Species File'
  project_citation: 'Plecoptera Species File'
  project_authors: 'DeWalt RE, Maehr MD, Hopkins H, Neu-Becker U, and Stueber G.'
  project_url: 'https://sfg-taxonpages.github.io/plecoptera'
  project_old_url: 'https://plecoptera.archive.speciesfile.org'
  focal_taxon: 'Plecoptera'
  focal_taxon_common_name: 'stoneflies'
  contact_email: 'dewalt@illinois.edu'
